name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Install Dependencies
        run: nix develop --command npm ci

      - name: Check Format
        run: nix develop --command npm run format:check

      - name: Lint
        run: nix develop --command npm run lint

      - name: Test
        run: nix develop --command npm run ci-test

      - name: Build Dist
        run: nix develop --command npm run package

      - name: Verify Dist is Up-to-Date
        run: |
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes in dist/. Run 'npm run package' and commit changes."
            git diff --ignore-space-at-eol --text dist/
            exit 1
          fi
